name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_and_test_publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ^3.10

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry
                  poetry install

            - name: Run tests and generate coverage report
              run: |
                  pip install pytest-cov
                  poetry run pytest --cov=utilki
                  poetry run coverage xml

            - name: Upload package to PyPI if commit is tagged with a version
              run: |
                  poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
                  poetry publish --build -n

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: false
